### Criar um novo projeto
POST http://localhost:8080/api/v1/projects
Content-Type: application/json

{
    "title": "Novo Projeto",
    "desc": "Descrição do projeto",
    "status": "ATIVO", 
    "team": {
        "nome": "Equipe X"
    },
    "problem": {
        "descricao": "Descrição do problema"
    },
    "objective": {
        "descricao": "Descrição do objetivo"
    },
    "activity": {
        "descricao": "Descrição da atividade"
    },
    "cause": {
        "descricao": "Descrição da causa"
    },
    "course": {
        "nome": "Curso de exemplo"
    }
}